import streamlit as st
from openai import OpenAI
import urllib.parse

# 1. PAGE CONFIG
st.set_page_config(page_title="Aura AI", page_icon="⭐", initial_sidebar_state="expanded")

# 2. BLUE ARROW CSS (Kept exactly as you liked it)
st.markdown("""
    <style>
        [data-testid="stSidebarCollapseIcon"] { color: #007BFF !important; background-color: #f0f2f6 !important; border-radius: 10px !important; padding: 5px !important; border: 2px solid #007BFF !important; width: 45px !important; height: 45px !important; }
        [data-testid="stHeader"] {background-color: rgba(0,0,0,0) !important;}
        #MainMenu, footer {visibility: hidden;}
    </style>
""", unsafe_allow_html=True)

# 3. SETUP
if "credits" not in st.session_state: st.session_state.credits = 50
if "all_chats" not in st.session_state: st.session_state.all_chats = {}
if "current_chat" not in st.session_state: st.session_state.current_chat = None

client = OpenAI(base_url="https://openrouter.ai/api/v1", api_key=st.secrets["OPENROUTER_API_KEY"])

# 4. SIDEBAR
with st.sidebar:
    st.title("Aura AI")
    st.metric("Credits Left", f"{st.session_state.credits}/50")
    if st.button("➕ New Chat", use_container_width=True):
        cid = f"Chat {len(st.session_state.all_chats) + 1}"
        st.session_state.all_chats[cid] = []
        st.session_state.current_chat = cid
        st.rerun()
    st.divider()
    for n in list(st.session_state.all_chats.keys()):
        if st.button(n, key=f"sidebar_{n}", use_container_width=True):
            st.session_state.current_chat = n
            st.rerun()

# 5. MAIN CHAT AREA
if st.session_state.current_chat:
    msgs = st.session_state.all_chats[st.session_state.current_chat]
    
    # This loop shows the history (including images)
    for m in msgs:
        with st.chat_message(m["role"]):
            if m.get("is_image"):
                st.image(m["content"], caption="Generated by Aura AI")
            else:
                st.markdown(m["content"])
    
    if p := st.chat_input("Ask me to draw something..."):
        st.session_state.credits = max(0, st.session_state.credits - 1)
        
        # KEYWORDS for Image Detection
        img_words = ["draw", "image", "photo", "picture", "make me a", "generate"]
        is_img = any(word in p.lower() for word in img_words)

        if is_img:
            # Clean the prompt for the AI
            clean_p = p.lower()
            for w in img_words: clean_p = clean_p.replace(w, "")
            clean_p = clean_p.replace("of", "").replace("can you", "").strip()
            
            # URL for the REAL image
            img_url = f"https://pollinations.ai/p/{urllib.parse.quote(clean_p)}?width=1024&height=1024&model=flux"
            
            # Show on screen
            with st.chat_message("user"):
